// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/event-service-platform/app/database/constant/currency"
	"backend/event-service-platform/app/database/constant/transaction"
	"backend/event-service-platform/app/database/entity"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserBalanceManager creates a new instance of MockUserBalanceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserBalanceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserBalanceManager {
	mock := &MockUserBalanceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserBalanceManager is an autogenerated mock type for the UserBalanceManager type
type MockUserBalanceManager struct {
	mock.Mock
}

type MockUserBalanceManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserBalanceManager) EXPECT() *MockUserBalanceManager_Expecter {
	return &MockUserBalanceManager_Expecter{mock: &_m.Mock}
}

// GetAllBalances provides a mock function for the type MockUserBalanceManager
func (_mock *MockUserBalanceManager) GetAllBalances(ctx context.Context, userID uuid.UUID) (map[string]int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBalances")
	}

	var r0 map[string]int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (map[string]int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) map[string]int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceManager_GetAllBalances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBalances'
type MockUserBalanceManager_GetAllBalances_Call struct {
	*mock.Call
}

// GetAllBalances is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserBalanceManager_Expecter) GetAllBalances(ctx interface{}, userID interface{}) *MockUserBalanceManager_GetAllBalances_Call {
	return &MockUserBalanceManager_GetAllBalances_Call{Call: _e.mock.On("GetAllBalances", ctx, userID)}
}

func (_c *MockUserBalanceManager_GetAllBalances_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserBalanceManager_GetAllBalances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserBalanceManager_GetAllBalances_Call) Return(stringToInt64 map[string]int64, err error) *MockUserBalanceManager_GetAllBalances_Call {
	_c.Call.Return(stringToInt64, err)
	return _c
}

func (_c *MockUserBalanceManager_GetAllBalances_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (map[string]int64, error)) *MockUserBalanceManager_GetAllBalances_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalanceByCurrency provides a mock function for the type MockUserBalanceManager
func (_mock *MockUserBalanceManager) GetBalanceByCurrency(ctx context.Context, userID uuid.UUID, cur currency.Currency) (map[string]int64, error) {
	ret := _mock.Called(ctx, userID, cur)

	if len(ret) == 0 {
		panic("no return value specified for GetBalanceByCurrency")
	}

	var r0 map[string]int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, currency.Currency) (map[string]int64, error)); ok {
		return returnFunc(ctx, userID, cur)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, currency.Currency) map[string]int64); ok {
		r0 = returnFunc(ctx, userID, cur)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, currency.Currency) error); ok {
		r1 = returnFunc(ctx, userID, cur)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceManager_GetBalanceByCurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalanceByCurrency'
type MockUserBalanceManager_GetBalanceByCurrency_Call struct {
	*mock.Call
}

// GetBalanceByCurrency is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - cur currency.Currency
func (_e *MockUserBalanceManager_Expecter) GetBalanceByCurrency(ctx interface{}, userID interface{}, cur interface{}) *MockUserBalanceManager_GetBalanceByCurrency_Call {
	return &MockUserBalanceManager_GetBalanceByCurrency_Call{Call: _e.mock.On("GetBalanceByCurrency", ctx, userID, cur)}
}

func (_c *MockUserBalanceManager_GetBalanceByCurrency_Call) Run(run func(ctx context.Context, userID uuid.UUID, cur currency.Currency)) *MockUserBalanceManager_GetBalanceByCurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 currency.Currency
		if args[2] != nil {
			arg2 = args[2].(currency.Currency)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserBalanceManager_GetBalanceByCurrency_Call) Return(stringToInt64 map[string]int64, err error) *MockUserBalanceManager_GetBalanceByCurrency_Call {
	_c.Call.Return(stringToInt64, err)
	return _c
}

func (_c *MockUserBalanceManager_GetBalanceByCurrency_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, cur currency.Currency) (map[string]int64, error)) *MockUserBalanceManager_GetBalanceByCurrency_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistory provides a mock function for the type MockUserBalanceManager
func (_mock *MockUserBalanceManager) GetHistory(ctx context.Context, userID uuid.UUID, _currency *currency.Currency, _type *transaction.TransactionType) ([]entity.UserBalanceTransaction, error) {
	ret := _mock.Called(ctx, userID, _currency, _type)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []entity.UserBalanceTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *currency.Currency, *transaction.TransactionType) ([]entity.UserBalanceTransaction, error)); ok {
		return returnFunc(ctx, userID, _currency, _type)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *currency.Currency, *transaction.TransactionType) []entity.UserBalanceTransaction); ok {
		r0 = returnFunc(ctx, userID, _currency, _type)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserBalanceTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *currency.Currency, *transaction.TransactionType) error); ok {
		r1 = returnFunc(ctx, userID, _currency, _type)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceManager_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type MockUserBalanceManager_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - _currency *currency.Currency
//   - _type *transaction.TransactionType
func (_e *MockUserBalanceManager_Expecter) GetHistory(ctx interface{}, userID interface{}, _currency interface{}, _type interface{}) *MockUserBalanceManager_GetHistory_Call {
	return &MockUserBalanceManager_GetHistory_Call{Call: _e.mock.On("GetHistory", ctx, userID, _currency, _type)}
}

func (_c *MockUserBalanceManager_GetHistory_Call) Run(run func(ctx context.Context, userID uuid.UUID, _currency *currency.Currency, _type *transaction.TransactionType)) *MockUserBalanceManager_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *currency.Currency
		if args[2] != nil {
			arg2 = args[2].(*currency.Currency)
		}
		var arg3 *transaction.TransactionType
		if args[3] != nil {
			arg3 = args[3].(*transaction.TransactionType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserBalanceManager_GetHistory_Call) Return(userBalanceTransactions []entity.UserBalanceTransaction, err error) *MockUserBalanceManager_GetHistory_Call {
	_c.Call.Return(userBalanceTransactions, err)
	return _c
}

func (_c *MockUserBalanceManager_GetHistory_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, _currency *currency.Currency, _type *transaction.TransactionType) ([]entity.UserBalanceTransaction, error)) *MockUserBalanceManager_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// RecordChange provides a mock function for the type MockUserBalanceManager
func (_mock *MockUserBalanceManager) RecordChange(ctx context.Context, userID uuid.UUID, cur currency.Currency, delta int64, txType transaction.TransactionType, source transaction.Source, status transaction.Status) (*entity.UserBalance, *entity.UserBalanceTransaction, error) {
	ret := _mock.Called(ctx, userID, cur, delta, txType, source, status)

	if len(ret) == 0 {
		panic("no return value specified for RecordChange")
	}

	var r0 *entity.UserBalance
	var r1 *entity.UserBalanceTransaction
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, currency.Currency, int64, transaction.TransactionType, transaction.Source, transaction.Status) (*entity.UserBalance, *entity.UserBalanceTransaction, error)); ok {
		return returnFunc(ctx, userID, cur, delta, txType, source, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, currency.Currency, int64, transaction.TransactionType, transaction.Source, transaction.Status) *entity.UserBalance); ok {
		r0 = returnFunc(ctx, userID, cur, delta, txType, source, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserBalance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, currency.Currency, int64, transaction.TransactionType, transaction.Source, transaction.Status) *entity.UserBalanceTransaction); ok {
		r1 = returnFunc(ctx, userID, cur, delta, txType, source, status)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.UserBalanceTransaction)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, currency.Currency, int64, transaction.TransactionType, transaction.Source, transaction.Status) error); ok {
		r2 = returnFunc(ctx, userID, cur, delta, txType, source, status)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserBalanceManager_RecordChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordChange'
type MockUserBalanceManager_RecordChange_Call struct {
	*mock.Call
}

// RecordChange is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - cur currency.Currency
//   - delta int64
//   - txType transaction.TransactionType
//   - source transaction.Source
//   - status transaction.Status
func (_e *MockUserBalanceManager_Expecter) RecordChange(ctx interface{}, userID interface{}, cur interface{}, delta interface{}, txType interface{}, source interface{}, status interface{}) *MockUserBalanceManager_RecordChange_Call {
	return &MockUserBalanceManager_RecordChange_Call{Call: _e.mock.On("RecordChange", ctx, userID, cur, delta, txType, source, status)}
}

func (_c *MockUserBalanceManager_RecordChange_Call) Run(run func(ctx context.Context, userID uuid.UUID, cur currency.Currency, delta int64, txType transaction.TransactionType, source transaction.Source, status transaction.Status)) *MockUserBalanceManager_RecordChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 currency.Currency
		if args[2] != nil {
			arg2 = args[2].(currency.Currency)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 transaction.TransactionType
		if args[4] != nil {
			arg4 = args[4].(transaction.TransactionType)
		}
		var arg5 transaction.Source
		if args[5] != nil {
			arg5 = args[5].(transaction.Source)
		}
		var arg6 transaction.Status
		if args[6] != nil {
			arg6 = args[6].(transaction.Status)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockUserBalanceManager_RecordChange_Call) Return(userBalance *entity.UserBalance, userBalanceTransaction *entity.UserBalanceTransaction, err error) *MockUserBalanceManager_RecordChange_Call {
	_c.Call.Return(userBalance, userBalanceTransaction, err)
	return _c
}

func (_c *MockUserBalanceManager_RecordChange_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, cur currency.Currency, delta int64, txType transaction.TransactionType, source transaction.Source, status transaction.Status) (*entity.UserBalance, *entity.UserBalanceTransaction, error)) *MockUserBalanceManager_RecordChange_Call {
	_c.Call.Return(run)
	return _c
}
