// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamhuutho/Event-Management-System/Event-Management-System-BE/event-service-platform/app/database/entity"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockItemManager creates a new instance of MockItemManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemManager {
	mock := &MockItemManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemManager is an autogenerated mock type for the ItemManager type
type MockItemManager struct {
	mock.Mock
}

type MockItemManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemManager) EXPECT() *MockItemManager_Expecter {
	return &MockItemManager_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function for the type MockItemManager
func (_mock *MockItemManager) CreateItem(ctx context.Context, item *entity.Item) (*entity.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *entity.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Item) (*entity.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Item) *entity.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemManager_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockItemManager_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entity.Item
func (_e *MockItemManager_Expecter) CreateItem(ctx interface{}, item interface{}) *MockItemManager_CreateItem_Call {
	return &MockItemManager_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, item)}
}

func (_c *MockItemManager_CreateItem_Call) Run(run func(ctx context.Context, item *entity.Item)) *MockItemManager_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Item
		if args[1] != nil {
			arg1 = args[1].(*entity.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemManager_CreateItem_Call) Return(item1 *entity.Item, err error) *MockItemManager_CreateItem_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *MockItemManager_CreateItem_Call) RunAndReturn(run func(ctx context.Context, item *entity.Item) (*entity.Item, error)) *MockItemManager_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItems provides a mock function for the type MockItemManager
func (_mock *MockItemManager) DeleteItems(ctx context.Context, ids []uuid.UUID) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItems")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockItemManager_DeleteItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItems'
type MockItemManager_DeleteItems_Call struct {
	*mock.Call
}

// DeleteItems is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockItemManager_Expecter) DeleteItems(ctx interface{}, ids interface{}) *MockItemManager_DeleteItems_Call {
	return &MockItemManager_DeleteItems_Call{Call: _e.mock.On("DeleteItems", ctx, ids)}
}

func (_c *MockItemManager_DeleteItems_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockItemManager_DeleteItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemManager_DeleteItems_Call) Return(err error) *MockItemManager_DeleteItems_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockItemManager_DeleteItems_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) error) *MockItemManager_DeleteItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function for the type MockItemManager
func (_mock *MockItemManager) GetItem(ctx context.Context, id uuid.UUID) (*entity.Item, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *entity.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Item, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Item); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemManager_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockItemManager_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockItemManager_Expecter) GetItem(ctx interface{}, id interface{}) *MockItemManager_GetItem_Call {
	return &MockItemManager_GetItem_Call{Call: _e.mock.On("GetItem", ctx, id)}
}

func (_c *MockItemManager_GetItem_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockItemManager_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemManager_GetItem_Call) Return(item *entity.Item, err error) *MockItemManager_GetItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemManager_GetItem_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Item, error)) *MockItemManager_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListItemsByCollectionIDs provides a mock function for the type MockItemManager
func (_mock *MockItemManager) ListItemsByCollectionIDs(ctx context.Context, collectionIDs []uuid.UUID, includeDeleted bool) ([]entity.Item, error) {
	ret := _mock.Called(ctx, collectionIDs, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for ListItemsByCollectionIDs")
	}

	var r0 []entity.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, bool) ([]entity.Item, error)); ok {
		return returnFunc(ctx, collectionIDs, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, bool) []entity.Item); ok {
		r0 = returnFunc(ctx, collectionIDs, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, collectionIDs, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemManager_ListItemsByCollectionIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItemsByCollectionIDs'
type MockItemManager_ListItemsByCollectionIDs_Call struct {
	*mock.Call
}

// ListItemsByCollectionIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionIDs []uuid.UUID
//   - includeDeleted bool
func (_e *MockItemManager_Expecter) ListItemsByCollectionIDs(ctx interface{}, collectionIDs interface{}, includeDeleted interface{}) *MockItemManager_ListItemsByCollectionIDs_Call {
	return &MockItemManager_ListItemsByCollectionIDs_Call{Call: _e.mock.On("ListItemsByCollectionIDs", ctx, collectionIDs, includeDeleted)}
}

func (_c *MockItemManager_ListItemsByCollectionIDs_Call) Run(run func(ctx context.Context, collectionIDs []uuid.UUID, includeDeleted bool)) *MockItemManager_ListItemsByCollectionIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockItemManager_ListItemsByCollectionIDs_Call) Return(items []entity.Item, err error) *MockItemManager_ListItemsByCollectionIDs_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockItemManager_ListItemsByCollectionIDs_Call) RunAndReturn(run func(ctx context.Context, collectionIDs []uuid.UUID, includeDeleted bool) ([]entity.Item, error)) *MockItemManager_ListItemsByCollectionIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type MockItemManager
func (_mock *MockItemManager) UpdateItem(ctx context.Context, item *entity.Item) (*entity.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *entity.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Item) (*entity.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Item) *entity.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemManager_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockItemManager_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entity.Item
func (_e *MockItemManager_Expecter) UpdateItem(ctx interface{}, item interface{}) *MockItemManager_UpdateItem_Call {
	return &MockItemManager_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, item)}
}

func (_c *MockItemManager_UpdateItem_Call) Run(run func(ctx context.Context, item *entity.Item)) *MockItemManager_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Item
		if args[1] != nil {
			arg1 = args[1].(*entity.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemManager_UpdateItem_Call) Return(item1 *entity.Item, err error) *MockItemManager_UpdateItem_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *MockItemManager_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, item *entity.Item) (*entity.Item, error)) *MockItemManager_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
