// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/event-service-platform/app/database/entity"
	"backend/event-service-platform/app/database/repository"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRarityConfigManager creates a new instance of MockRarityConfigManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRarityConfigManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRarityConfigManager {
	mock := &MockRarityConfigManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRarityConfigManager is an autogenerated mock type for the RarityConfigManager type
type MockRarityConfigManager struct {
	mock.Mock
}

type MockRarityConfigManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRarityConfigManager) EXPECT() *MockRarityConfigManager_Expecter {
	return &MockRarityConfigManager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRarityConfigManager
func (_mock *MockRarityConfigManager) Create(ctx context.Context, rc *entity.RarityConfig) (*entity.RarityConfig, error) {
	ret := _mock.Called(ctx, rc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.RarityConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RarityConfig) (*entity.RarityConfig, error)); ok {
		return returnFunc(ctx, rc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RarityConfig) *entity.RarityConfig); ok {
		r0 = returnFunc(ctx, rc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RarityConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.RarityConfig) error); ok {
		r1 = returnFunc(ctx, rc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRarityConfigManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRarityConfigManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *entity.RarityConfig
func (_e *MockRarityConfigManager_Expecter) Create(ctx interface{}, rc interface{}) *MockRarityConfigManager_Create_Call {
	return &MockRarityConfigManager_Create_Call{Call: _e.mock.On("Create", ctx, rc)}
}

func (_c *MockRarityConfigManager_Create_Call) Run(run func(ctx context.Context, rc *entity.RarityConfig)) *MockRarityConfigManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.RarityConfig
		if args[1] != nil {
			arg1 = args[1].(*entity.RarityConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRarityConfigManager_Create_Call) Return(rarityConfig *entity.RarityConfig, err error) *MockRarityConfigManager_Create_Call {
	_c.Call.Return(rarityConfig, err)
	return _c
}

func (_c *MockRarityConfigManager_Create_Call) RunAndReturn(run func(ctx context.Context, rc *entity.RarityConfig) (*entity.RarityConfig, error)) *MockRarityConfigManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function for the type MockRarityConfigManager
func (_mock *MockRarityConfigManager) GetByCode(ctx context.Context, code string) (*entity.RarityConfig, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *entity.RarityConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.RarityConfig, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.RarityConfig); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RarityConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRarityConfigManager_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type MockRarityConfigManager_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockRarityConfigManager_Expecter) GetByCode(ctx interface{}, code interface{}) *MockRarityConfigManager_GetByCode_Call {
	return &MockRarityConfigManager_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *MockRarityConfigManager_GetByCode_Call) Run(run func(ctx context.Context, code string)) *MockRarityConfigManager_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRarityConfigManager_GetByCode_Call) Return(rarityConfig *entity.RarityConfig, err error) *MockRarityConfigManager_GetByCode_Call {
	_c.Call.Return(rarityConfig, err)
	return _c
}

func (_c *MockRarityConfigManager_GetByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*entity.RarityConfig, error)) *MockRarityConfigManager_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRarityConfigManager
func (_mock *MockRarityConfigManager) GetByID(ctx context.Context, id uuid.UUID) (*entity.RarityConfig, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.RarityConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.RarityConfig, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.RarityConfig); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RarityConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRarityConfigManager_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRarityConfigManager_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRarityConfigManager_Expecter) GetByID(ctx interface{}, id interface{}) *MockRarityConfigManager_GetByID_Call {
	return &MockRarityConfigManager_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRarityConfigManager_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRarityConfigManager_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRarityConfigManager_GetByID_Call) Return(rarityConfig *entity.RarityConfig, err error) *MockRarityConfigManager_GetByID_Call {
	_c.Call.Return(rarityConfig, err)
	return _c
}

func (_c *MockRarityConfigManager_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.RarityConfig, error)) *MockRarityConfigManager_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRarityConfigManager
func (_mock *MockRarityConfigManager) List(ctx context.Context, filter repository.RarityConfigFilter) ([]entity.RarityConfig, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.RarityConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RarityConfigFilter) ([]entity.RarityConfig, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RarityConfigFilter) []entity.RarityConfig); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RarityConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.RarityConfigFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRarityConfigManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRarityConfigManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.RarityConfigFilter
func (_e *MockRarityConfigManager_Expecter) List(ctx interface{}, filter interface{}) *MockRarityConfigManager_List_Call {
	return &MockRarityConfigManager_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockRarityConfigManager_List_Call) Run(run func(ctx context.Context, filter repository.RarityConfigFilter)) *MockRarityConfigManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.RarityConfigFilter
		if args[1] != nil {
			arg1 = args[1].(repository.RarityConfigFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRarityConfigManager_List_Call) Return(rarityConfigs []entity.RarityConfig, err error) *MockRarityConfigManager_List_Call {
	_c.Call.Return(rarityConfigs, err)
	return _c
}

func (_c *MockRarityConfigManager_List_Call) RunAndReturn(run func(ctx context.Context, filter repository.RarityConfigFilter) ([]entity.RarityConfig, error)) *MockRarityConfigManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRarityConfigManager
func (_mock *MockRarityConfigManager) Update(ctx context.Context, rc *entity.RarityConfig) (*entity.RarityConfig, error) {
	ret := _mock.Called(ctx, rc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.RarityConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RarityConfig) (*entity.RarityConfig, error)); ok {
		return returnFunc(ctx, rc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RarityConfig) *entity.RarityConfig); ok {
		r0 = returnFunc(ctx, rc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RarityConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.RarityConfig) error); ok {
		r1 = returnFunc(ctx, rc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRarityConfigManager_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRarityConfigManager_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *entity.RarityConfig
func (_e *MockRarityConfigManager_Expecter) Update(ctx interface{}, rc interface{}) *MockRarityConfigManager_Update_Call {
	return &MockRarityConfigManager_Update_Call{Call: _e.mock.On("Update", ctx, rc)}
}

func (_c *MockRarityConfigManager_Update_Call) Run(run func(ctx context.Context, rc *entity.RarityConfig)) *MockRarityConfigManager_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.RarityConfig
		if args[1] != nil {
			arg1 = args[1].(*entity.RarityConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRarityConfigManager_Update_Call) Return(rarityConfig *entity.RarityConfig, err error) *MockRarityConfigManager_Update_Call {
	_c.Call.Return(rarityConfig, err)
	return _c
}

func (_c *MockRarityConfigManager_Update_Call) RunAndReturn(run func(ctx context.Context, rc *entity.RarityConfig) (*entity.RarityConfig, error)) *MockRarityConfigManager_Update_Call {
	_c.Call.Return(run)
	return _c
}
