// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamhuutho/Event-Management-System/Event-Management-System-BE/event-service-platform/app/manager"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCollectionManager creates a new instance of MockCollectionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectionManager {
	mock := &MockCollectionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollectionManager is an autogenerated mock type for the CollectionManager type
type MockCollectionManager struct {
	mock.Mock
}

type MockCollectionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectionManager) EXPECT() *MockCollectionManager_Expecter {
	return &MockCollectionManager_Expecter{mock: &_m.Mock}
}

// DeleteCollection provides a mock function for the type MockCollectionManager
func (_mock *MockCollectionManager) DeleteCollection(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCollectionManager_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type MockCollectionManager_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCollectionManager_Expecter) DeleteCollection(ctx interface{}, id interface{}) *MockCollectionManager_DeleteCollection_Call {
	return &MockCollectionManager_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, id)}
}

func (_c *MockCollectionManager_DeleteCollection_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCollectionManager_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollectionManager_DeleteCollection_Call) Return(err error) *MockCollectionManager_DeleteCollection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCollectionManager_DeleteCollection_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockCollectionManager_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// ListCollections provides a mock function for the type MockCollectionManager
func (_mock *MockCollectionManager) ListCollections(ctx context.Context, filter manager.ListCollectionsFilter) ([]manager.CollectionWithItems, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListCollections")
	}

	var r0 []manager.CollectionWithItems
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manager.ListCollectionsFilter) ([]manager.CollectionWithItems, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manager.ListCollectionsFilter) []manager.CollectionWithItems); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]manager.CollectionWithItems)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manager.ListCollectionsFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionManager_ListCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCollections'
type MockCollectionManager_ListCollections_Call struct {
	*mock.Call
}

// ListCollections is a helper method to define mock.On call
//   - ctx context.Context
//   - filter manager.ListCollectionsFilter
func (_e *MockCollectionManager_Expecter) ListCollections(ctx interface{}, filter interface{}) *MockCollectionManager_ListCollections_Call {
	return &MockCollectionManager_ListCollections_Call{Call: _e.mock.On("ListCollections", ctx, filter)}
}

func (_c *MockCollectionManager_ListCollections_Call) Run(run func(ctx context.Context, filter manager.ListCollectionsFilter)) *MockCollectionManager_ListCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manager.ListCollectionsFilter
		if args[1] != nil {
			arg1 = args[1].(manager.ListCollectionsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollectionManager_ListCollections_Call) Return(collectionWithItemss []manager.CollectionWithItems, err error) *MockCollectionManager_ListCollections_Call {
	_c.Call.Return(collectionWithItemss, err)
	return _c
}

func (_c *MockCollectionManager_ListCollections_Call) RunAndReturn(run func(ctx context.Context, filter manager.ListCollectionsFilter) ([]manager.CollectionWithItems, error)) *MockCollectionManager_ListCollections_Call {
	_c.Call.Return(run)
	return _c
}
