# ConfigMap cho event-service
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-service-config
  namespace: default
data:
  config-local: |
    server:
      port: 8080

    database:
      protocol: postgresql
      url: postgres
      replica_url: postgres
      name: event_management
      username: postgres
      password: postgres
      port: 5432
      ssl_mode: disable
      max_db_conns: 10
      max_idle_db_conns: 10

    redis:
      hosts: redis:6379
      pool_size: 10

    jwt:
      secret_key: "11111111-1111-1111-1111-111111111111"
      access_expiration: 24h
