# Rollout - Canary Deployment cho Event Service
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: event-service
  namespace: default
  labels:
    app: event-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: docker.io/library/event-service:latest  # Load từ minikube
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
  strategy:
    canary:
      canaryService: event-service-canary
      stableService: event-service-stable
      steps:
        - setWeight: 10
        - pause: {}           # Dừng ở đây - check log
        - setWeight: 30
        - pause: {duration: 3}
        - setWeight: 50
        - pause: {duration: 3}
        - setWeight: 100
