# Default to port 5433 for local development to avoid colliding with host Postgres on 5432.
flyway.url=jdbc:postgresql://localhost:5433/eventserviceplatformtpl
flyway.user=local
flyway.password=local
flyway.locations=filesystem:./

flyway.sqlMigrationPrefix=
flyway.sqlMigrationSeparator=-
flyway.table=schema_version
flyway.cleanDisabled=false
flyway.baselineOnMigrate=false
